dist: xenial
language: python
python:
    - 3.5
    - 3.6
    - 3.7

install:
    - pip install .[dev]
    - pip install coveralls

script:
    - coverage run --source . test.py
    - ckp --help

after_success:
    - coveralls
